spring:
#application:
#name: MyMindMate
  profiles:
    active: local #prod local  , mysql

  # smtp
  mail:
    host: smtp.naver.com          # 네이버 SMTP 서버 주소
    port: 465                     # 네이버 SMTP 포트 번호
    username: mymindmate@naver.com    # 네이버 이메일
    password: mymindmate0212!         # 네이버 비밀번호
    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 여부
          ssl:
            enable: true
            trust: smtp.naver.com

server:
  port: 8080
  servlet:
    session:
      timeout: 30m  # 사용자 활동 할 때마다 세션 시간 갱신
