spring:
#application:
#name: MyMindMate
  profiles:
    active: local  #prod, mysql

  # smtp
  mail:
    host: smtp.naver.com          # 네이버 SMTP 서버 주소
    port: 465                     # 네이버 SMTP 포트 번호
    username: mymindmate@naver.com    # 네이버 이메일
    password: mymindmate0212!         # 네이버 비밀번호
    properties:
      mail:
        smtp:
          auth: true              # 사용자 인증 여부
          ssl:
            enable: true
            trust: smtp.naver.com


# fcm
fcm:
  file_path: firebase/mmm_fcm.json
  url: https://fcm.googleapis.com/v1/projects/mymindmate-5dae7/messages:send
  google_api: https://www.googleapis.com/auth/cloud-platform
  project_id: mymindmate-5dae7